name: Azure Function App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies (for linting/tests only)
        run: |
          cd AED-functionapp
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (opcjonalnie: możesz dodać testy jednostkowe tutaj)

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App (with remote build)
        uses: Azure/functions-action@v1
        with:
          app-name: AED-functionapp
          package: ./AED-functionapp
          enable-oryx-build: true  # wymusza zdalną instalację zależności w Azure
